app_port: 80
pip_install_packages:
  - name: docker
    version: "6.1.3"
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: datadoghq.eu
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: check service
        url: "http://localhost:{{ app_port }}/ping"
        timeout: 10
        method: GET