- hosts: all
  roles:
    - role: geerlingguy.pip
      become: yes

  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      tags: datadog
      become: yes
      import_role:
        name: datadog.dd.agent
    - name: deploy app
      tags: deploy
      become: yes
      community.docker.docker_container:
        name: flask-app
        image: mercuriaal/simple-flask-app:latest
        ports:
          - "{{ app_port }}:5000"
        restart: true
        pull: true
        recreate: true